spring:
    # Servlet 配置
    servlet:
        # 文件上传相关配置项
        multipart:
            # 单个文件大小
            max-file-size: 16MB
            # 设置总上传的文件大小
            max-request-size: 32MB

    # Jackson 配置项
    jackson:
        serialization:
            write-dates-as-timestamps: true # 设置 Date 的格式，使用时间戳
            write-date-timestamps-as-nanoseconds: false # 设置不使用 nanoseconds 的格式。例如说 1611460870.401，而是直接 1611460870401
            write-durations-as-timestamps: true # 设置 Duration 的格式，使用时间戳
            fail-on-empty-beans: false # 允许序列化无属性的 Bean

# MyBatis Plus 的配置项
mybatis-plus:
    configuration:
        map-underscore-to-camel-case: true
    global-config:
        db-config:
            id-type: assign_id
            logic-delete-value: 1
            logic-not-delete-value: 0
        banner: false
    type-aliases-package: com.jackwu.module.course.dal.dataobject





debug: false
