spring:
    main:
        # 设置为 true 会导致 swagger 文档报错
        lazy-initialization: false
        # 运行循环依赖
        allow-circular-references: true
    # Servlet 配置
    servlet:
        # 文件上传相关配置项
        multipart:
            # 单个文件大小
            max-file-size: 16MB
            # 设置总上传的文件大小
            max-request-size: 32MB

    mvc:
        pathmatch:
            # 解决 SpringFox 与 SpringBoot 2.6.x 不兼容的问题，
            matching-strategy: ANT_PATH_MATCHER

    # Jackson 配置项
    jackson:
        serialization:
            # 设置 Date 的格式，使用时间戳
            write-dates-as-timestamps: true
            # 设置不使用 nanoseconds 的格式。例如说 1611460870.401，而是直接 1611460870401
            write-date-timestamps-as-nanoseconds: false
            # 设置 Duration 的格式，使用时间戳
            write-durations-as-timestamps: true
            # 允许序列化无属性的 Bean
            fail-on-empty-beans: false

--- #################### mybatis-plus相关配置 ####################

mybatis-plus:
    configuration:
        map-underscore-to-camel-case: true
        log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    global-config:
        db-config:
            id-type: auto
            logic-delete-value: 1
            logic-not-delete-value: 0
        banner: false
    type-aliases-package: com.jackwu.module.system.dal.dataobject

--- #################### redis相关配置 ####################
# 端口
spring:
    # redis配置
    redis:
        # Redis数据库索引（默认为0）
        database: 0
        # Redis服务器地址
        host: 127.0.0.1
        # Redis服务器连接端口
        port: 6379
        # Redis服务器连接密码（默认为空）
        # password:
        # 连接超时时间
        timeout: 10s
        lettuce:
            pool:
                # 连接池最大连接数
                max-active: 200
                # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1ms
                # 连接池中的最大空闲连接
                max-idle: 16
                # 连接池中的最小空闲连接
                min-idle: 4

--- #################### Sa-Token 相关配置 ####################

sa-token:
    # token名称 (同时也是cookie名称)
    token-name: Authorization
    # token有效期 设为一天 (必定过期) 单位: 秒
    timeout: 86400
    # token临时有效期 (指定时间无操作就过期) 单位: 秒
    activity-timeout: 1800
    # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
    is-concurrent: false
    # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
    is-share: false
    # 是否尝试从cookie里读取token
    is-read-cookie: false
    # token前缀
    token-prefix: "Bearer"
    # jwt秘钥
    jwt-secret-key: tqwe6rwe78rcw87r56tgv4556fdete8t7ew786
    # 是否输出操作日志
    is-log: true
    # 是否打印banner
    is-print: false
    token-style: simple-uuid

--- #################### swagger 相关配置 ####################

edu:
    swagger:
        enable: true
        author: jackwu
        title: 系统模块
        description: 提供系统管理, 配置相关的功能
        version: 1.0.0



